<?php

namespace backend\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "goods".
 *
 * @property integer $id
 * @property string $name
 * @property string $sn
 * @property string $logo
 * @property integer $goods_category_id
 * @property integer $brand_id
 * @property string $market_price
 * @property string $shop_price
 * @property integer $stock
 * @property integer $is_on_sale
 * @property integer $status
 * @property integer $sort
 * @property integer $create_time
 */
class Goods extends \yii\db\ActiveRecord
{
    public static $saleOptions = [1=>'在售',0=>'下架'];
    public static $statusOptions = [1=>'正常',0=>'回收站'];

    public function getGoodsCategory(){
        return $this->hasOne(GoodsCategory::className(),['id'=>'goods_category_id']);
    }
    public function getBrandCategory(){
        return $this->hasOne(Brand::className(),['id'=>'brand_id']);
    }
    public function getGoodsIntro(){
        return $this->hasOne(GoodsIntro::className(),['goods_id'=>'id']);
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'goods';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'goods_category_id', 'shop_price', 'stock', 'is_on_sale', 'status', 'sort', ], 'required'],
            [['goods_category_id', 'brand_id', 'stock', 'is_on_sale', 'status', 'sort', 'create_time'], 'integer'],
            [['market_price', 'shop_price'], 'number'],
            [['name', 'sn'], 'string', 'max' => 20],
            [['logo'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '商品名称',
            'sn' => '货号',
            'logo' => 'LOGO图片',
            'goods_category_id' => '商品分类',
            'brand_id' => '品牌分类',
            'market_price' => '市场价格',
            'shop_price' => '商品价格',
            'stock' => '库存',
            'is_on_sale' => '是否在售',
            'status' => '状态',
            'sort' => '排序',
            'create_time' => '添加时间',
            'imgFile' => 'LOGO'
        ];
    }
    static public function getBrand(){
        return ArrayHelper::map(Brand::find()->asArray()->all(),'id','name');
    }
    public function beforeSave($insert)
    {
        if ($insert){//添加时

            if (!$count = GoodsDayCount::findOne(['day'=>date('Ymd')])){
                $count = new GoodsDayCount();
                $count->day = date('Ymd');
                $count->count = 0;
            }
            $count->count = $count->count + 1;
            $count->save();
            $this->sn = date('Ymd').str_pad($count->count,5,"0",STR_PAD_LEFT);
            $this->create_time = time();

        }else{

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function getImg(){
        return $this->hasMany(GoodsPhoto::className(),['goods_id'=>'id']);
    }
    public function getBrandName(){
        return $this->hasOne(Brand::className(),['id'=>'brand_id']);
    }
    public function getGoodsContent(){
        return $this->hasOne(GoodsIntro::className(),['goods_id'=>'id']);
    }
}
