<?php
namespace backend\widgets;

//use yii\bootstrap\Widget;
use backend\models\Menu;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use Yii;

class MenuWidget extends \yii\base\Widget {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        NavBar::begin([
            'brandLabel' => '嘿嘿商城后台',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);
        /*$menuItems = [
            ['label'=>'商品列表','url'=>['/goods/index']],
            ['label'=>'商品分类列表','url'=>['/goods-category/index']],
            ['label'=>'品牌列表','url'=>['/brand/index']],
            ['label'=>'用户列表','url'=>['/user/index']],
//        ['label' => '修改密码', 'url' => ['/user/pwd']],
        ];*/


        if (Yii::$app->user->isGuest) {
            $menuItems[] = ['label' => '登录', 'url' => Yii::$app->user->loginUrl];
        } else {
            $menus = Menu::findAll(['parent_id'=>0]);
            foreach ($menus as $menu){
                $item = ['label'=>$menu->label,'items'=>[]];
//                foreach (Menu::find()->where(['parent_id'=>$menu->id])->all() as $child){
                foreach ($menu->children as $child){
                    if (Yii::$app->user->can($child->url)){
                        $item['items'][] = ['label' => $child->label, 'url' => [$child->url]];
                    }
                }
                if (!empty($item['items'])){
                    $menuItems[] = $item;
                }
            }
            $menuItems[] = ['label'=>'退出('.\Yii::$app->user->identity->username.')','url'=>['/user/logout']];
        }
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => $menuItems,
        ]);
        NavBar::end();
        parent::run(); // TODO: Change the autogenerated stub
    }
}