<?php
namespace frontend\widgets;

use backend\models\GoodsCategory;
use yii\base\Widget;

class CategoryWidget extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        /*$redis = new \Redis();
        $redis->connect();
        $category_html = $redis->get('category_html');
        if ($category_html == null){*/
            $catetorys = GoodsCategory::findAll(['parent_id'=>0]);
            $category_html = $this->renderFile('@app/widgets/views/category.php',['categorys'=>$catetorys]);
//        }
        return $category_html;
    }
}